version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        build: ./requirements/nginx/
        ports:
            - 443:443
        volumes:
            - wp_data:/var/www/html
        depends_on:
            - wordpress
        networks:
            - front
        restart: always

    wordpress:
        image: wordpress
        container_name: wordpress
        build: requirements/wordpress
        volumes:
            - wp_data:/var/www/html
        env_file:
            - ./.env
        depends_on:
            - mariadb
        networks:
            - front
            - back
        restart: always

    mariadb:
        image: mariadb
        container_name: mariadb
        build: ./requirements/mariadb
        volumes:
            - db:/var/lib/mysql
        env_file:
            - .env
        networks:
            - back
        restart: always
        
networks:
    front:
        driver: bridge
    back:
        driver: bridge
volumes:
    wp_data:
        driver: local
        driver_opts:
            type: none
            device: /home/stfernan/data/html
            o: bind
    db:
        driver: local
        driver_opts:
            type: none
            device: /home/stfernan/data/mysql
            o: bind
